### PR TITLE
Elevate lineage XEC as clade 24F

### PR DESCRIPTION
**Pull request by trvrb**
With this PR, we are designating clade 24F (lineage XEC) and 24G (lineage KP.2.3)

#### Clade 24F, lineage XEC

Clade 24F, lineage XEC stems from a rather complex recombination event. Some discussion is visible at https://github.com/cov-lineages/pango-designation/issues/2717. One parent is KS.1.1 and the other parent is KP.3.3. KS.1.1 belongs to clade 24A (lineage JN.1) and KP.3.3 belongs to clade 24C (lineage KP.3), which itself descends from JN.1. So this is recombinant of JN.1-derived diversity. The breakpoint is around 21738~22599, right around the spike junction which is common.

XEC likely originated somewhere in Central Europe, being particularly common early on in Germany, Czechia, and Austria, with first sequences collected in June 2024.

The mutational make-up relative to previously dominant lineage KP.3.1.1 can be seen on Cov-Spectrum: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=XEC&pangoLineage1=KP.3.1.1&analysisMode=CompareEquals&, where XEC bears the amino acid mutations ORF1a:A599T, S:T22N, S:F59S, N:G204P, ORF9b:P3H relative to KP.3.1.1. It's not immediately clear to me if the fitness of this lineage is due to the two spike mutations vs mutations elsewhere in the genome. @ryhisner discusses potential molecular change to nucleocapsid (N) here: https://x.com/LongDesertTrain/status/1837346366961451290

When forcing a regular bifurcating phylogeny (as the ncov workflow does), XEC shows up as derived from its parent KP.3.3.

At the moment, the latest Nextclade dataset was [released on July 17](https://github.com/nextstrain/nextclade_data/pull/216) and doesn't contain XEC. Because of this, many of the normally referenced data systems also don't contain XEC. In the below, I've instead worked from the `pango_lineage` metadata provided by GISAID rather than the `Nextclade_pango` calls.

Running https://github.com/nextstrain/forecasts-ncov on `pango_lineage` counts results in an estimated fitness of 1.7 relative to clade 24A / lineage JN.1 and is currently significantly greater than other lineages:

pango-fitness

This results in the prediction of XEC becoming dominant over KP.3.1.1 in most countries in late October:

pango-frequency

If we look at frequency in the USA vs fitness, we see that XEC is currently inferred to be the 2nd most common Pango lineage (behind KP.3.1.1) and have the highest fitness relative to the population average:

freq_vs_ga_2024-09-25

If we do a simple lineage regression of logit transformed frequencies for countries with data we get the following:

xec_logistic-growth-transformed-axis

The average per-day growth rate is 0.07 and current predicted frequency varies in these countries between 5% and 23%.

Thus, 24D / XDV.1 fulfills our [clade designation criteria](https://nextstrain.org/blog/2022-04-29-SARS-CoV-2-clade-naming-2022) 4: "A clade shows consistent >0.05 per day growth in frequency where it's circulating and has reached >5% regional frequency".

#### Clade 24G, lineage KP.2.3

Clade 24G, lineage KP.2.3, is a descendant of clade 24B (JN.1.11.1=KP) with extra spike substitutions S:R346T, S:H146Q and deletion S:S31-, and ORF3a:K67N.

KP.2.3 was first commonly observed in India, with first sequences from January 2024.

It was among the fittest lineages until KP.3, KP.3.1.1 and XEC came around and is still common in various countries around the globe, in particular Brazil, Singapore, India, and likely other countries in South East Asia with limited surveillance based on the high prevalence in Singapore.

In sequences collected in June and July 2024, per cov-spectrum, it was:
- 57% in Cuba
- 44% in Singapore
- 41% in Guatemala
- 28% in Malaysia
- 28% in India
- 26% in Guatemala

In sequences collected since August 2024, it was 38% in Brazil.

It satisfied clade criterion 4 "A clade shows consistent >0.05 per day growth in frequency where it's circulating and has reached >5% regional frequency" in sequences collected in April/May in Asia and only narrowly misses the regional criterion 3 in South America and Asia.

One reason KP.2.3 is only elevated now is that its high prevalence in many countries around the globe became only clear gradually due to delayed sequence upload. KP.2.3 is particularly prevalent in countries with relatively low sequencing intensity and long delays.

Another reason for designation is that KP.2.3 is a direct descendant of the US-recommended vaccine strain KP.2 (for Moderna/Pfizer, i.e. mRNA).

Brave Browser 2024-10-03 15 54 25

Prevalence and growth in Asia in months April and May 2024:

Brave Browser 2024-10-03 16 04 58

Brave Browser 2024-10-03 16 05 07

### Pre-merge checklist

- [x] ncov file updates:
  - defaults/clades.tsv
  - defaults/clade_emergence_dates.tsv
  - defaults/clade_hierarchy.tsv
  - defaults/clades_display_names.yml
  - defaults/color_ordering.tsv
  - defaults/emerging_lineages.tsv (if needed)
- [x] ncov-ingest file update: https://github.com/nextstrain/ncov-ingest/blob/master/defaults/clade-legacy-mapping.yml
- [x] Explain in PR why we are elevating
- [ ] Check trial builds:
  - [ ] https://nextstrain.org/staging/ncov/gisaid/trial/clades-2024-10/north-america/all-time  
  - [ ] https://nextstrain.org/staging/ncov/open/trial/clades-2024-10/north-america/all-time
- [ ] PR approval

### Post merge checklist

- [ ] Add new variant (with new name) to Nextclade dataset color_ordering.tsv
- [ ] Update [clade diagram figure](https://github.com/nextstrain/ncov-clades-schema)
- [ ] Trigger full runs on GISAID & Genbank once Nextclade updated
- [ ] Tweet about new variant

### CODE REVIEW

**Comment by aviczhl2** [comment]
ORF1a:A599T is not included in all XEC*s, another Orf1a:1367 branch is designated XEC.2 so not included in raw XEC seqs without *.

**Comment by corneliusroemer** [comment]
Hah, I came here to make this PR, didn't know it existed already, thanks @trvrb. I'll also add KP.2.3, since it also satisfies the criteria.

**Review by corneliusroemer — APPROVED** [review]
I'll make trial builds

**Comment by corneliusroemer** [comment]
Test build looks good:
image

**Comment by corneliusroemer** [comment]
I discussed this PR yesterday with @rneher and he gave verbal approval so I will merge this. 

Open also looks great

image

**Comment by trvrb** [comment]
@corneliusroemer: Amazing! Thanks so much for cleaning things up and adding clade 24G / lineage KP.2.3. Everything here looks great to me.

**Pull request merged**
