### PR TITLE
Replace environment.yml with requirements.txt

### PR DESCRIPTION
**Pull request by kairstenfay**
Other users had some problems installing the conda environment from the
`environment.yml` I had exported and added to this repo. Change instead
to the simpler, `requirements.txt` for dependency tracking via
`pip freeze`. Upate the README accordingly.

### CODE REVIEW

**Comment by kairstenfay** [comment]
Sorry, this is wrong. For some reason my `pip` path maps to a Pipenv instead of the appropriate conda environment. I'll push a fix.

**Comment by kairstenfay** [comment]
Ok, now the `requirements.txt` file is correct.

**Comment by jameshadfield** [comment]
Thanks @kairstenfay -- the requirements.txt has 50 (!) dependencies -- I would have only expected `aws` and `augur` (and maybe `nextstrain-cli`)

**Comment by tsibley** [comment]
Wrote this in Slack, but for posterity here:

> I would expect nextstrain/ncov to not have a requirements.txt or environment.yml, similar to our other pathogen builds.
> 
> We do document how to get a Nextstrain environment (either via conda or via nextstrain build) in the "Building" section: https://github.com/nextstrain/ncov#building

**Comment by kairstenfay** [comment]
Closing in favor of #58

**Pull request closed without merging**
