### PR TITLE
Adds translators name.

### PR DESCRIPTION
**Pull request by cassiawag**

### CODE REVIEW

**Comment by tomoyuki-nezu** [comment]
Hello @cassiawag 
Thank you for taking the time.
It seems that the merge result to the master branch is not update on the nextstain.com site, can you please update it?

**Comment by cassiawag** [comment]
I'm sorry about that, @tomoyuki-nezu. Updated now! Thanks for letting me know.

**Comment by tomoyuki-nezu** [comment]
@cassiawag Thank you for taking time out of your busy schedule.

**Comment by cassiawag** [comment]
No problem! :)

**Pull request merged**
