### PR TITLE
Designate clades 23G (XBB.1.5.70), 23H (HK.3), 23I (BA.2.86)

### PR DESCRIPTION
**Pull request by corneliusroemer**
[DRAFT PROPOSAL]

With this PR, we are designating 3 new Nextstrain clades:

- 23G = XBB.1.5.70
- 23H = HK.3 (= EG.5.1.1.3 = XBB.1.9.2.5.1.1.3)
- 23I = BA.2.86

#### 23G = XBB.1.5.70

23G = XBB.1.5.70 is a sublineage of 23A = XBB.1.5 with extra spike receptor binding domain mutations L455F and F456L. It emerged in early 2023 in South America, becoming dominant in Brazil around September 2023. In the second half of 2023, it was responsible for more than a third of global XBB.1.5-derived sequences. It is notable as the first successful XBB lineage with FLip genotype (L455F and F456L). In sequences collected since 2023-09-01, it is most common in Asia, in particular China and Singapore (50%), South Korea (31%) and Malaysia (25%). It is also common , in particular Brazil (48%), Chile (27%), Argentina (23%) and Colombia (12%). Outside of South America, it is most common in Australia (17%) and Finland (16%). It is generally at around 5% in Europe and North America. Japan (8%) and Italy (5%). It is at between 1-5% in North America and Europe. 

It satisfies clade criterion 3: "A clade reaches >30% regional frequency for 2 or more months" for the region of South America.

Below is a 6m South America tree showing 23G (XBB.1.5.70) in grey:
image
https://nextstrain.org/staging/ncov/gisaid/21L/trial/clades-2023-11/south-america/6m?f_region=South%20America

#### 23H = HK.3 (= EG.5.1.1.3 = XBB.1.9.2.5.1.1.3)

23H = HK.3 (= EG.5.1.1.3 = XBB.1.9.2.5.1.1.3) is the biggest sublineage of 23F (EG.5.1) with RBD mutation L455F and hence FLip genotype (23F already has F456L). It emerged around May-June 2023 in China where it became dominant in September 2023. While L455F has occurred many times independently within EG.5.1, HK.3 alone makes up more than half of globally sequenced EG.5.1 with that genotype. In sequences collected since 2023-09-01, it is most common in South America, in particular Brazil (48%), Chile (27%), Argentina (23%) and Colombia (12%). Outside of South America, it is most common in Japan (8%) and Italy (5%). It is at around 5% in North America and Europe, generally, and 1% in South America.

It satisfies clade criterion 3: "A clade reaches >30% regional frequency for 2 or more months" for the region of Asia.

Below is a 2m Asia tree showing 23H (HK.3) in orange at the top:

image

#### 23I = BA.2.86

23I = BA.2.86 represents the most significant evolutionary jump since the emergence of the Omicrons. It is a descendant of BA.2 but with more than 30 spike mutations. It emerged in July 2023, likely in Southern Africa, and has grown rapidly worldwide, doubling in proportion roughly every 2 weeks. In sequences with collection date in October 2023, it was most commonly found in Europe and Africa, in particular in Portugal (22%), Iceland (21%), South Africa (19%), Denmark (15%), and Mauritius (12%). In October, per continent, it was 13% in Africa, 7% in Europe, 3.5% in Oceania, 1.8% in Asia, 1.3% in North America and 0.2% in South America.

BA.2.86 sublineage JN.1 (BA.2.86.1.1) with extra RBD mutation L455S shows a further increase in growth advantage, doubling in share a little slower than weekly. JN.1 emerged in August 2023, likely in Europe, and in sequences from October 2023 was most common in Iceland (19%), Portugal (14%), France (5%) and Denmark (4%). In sequences collected in early November 2023, JN.1 made up already around half of all BA.2.86* sequences.

BA.2.86 satisfies clade criterion 4: "A clade shows consistent >0.05 per day growth in frequency where it’s circulating and has reached >5% regional frequency" for the region of Europe (and North America).

While sublineage JN.1 is particularly successful, we designate the parent BA.2.86 as the genetic differences between BA.2 and BA.2.86 are much larger than between BA.2.86 and JN.1.

Below is a Europe 2m tree showing 23I (BA.2.86) in red:
image
https://nextstrain.org/staging/ncov/gisaid/21L/trial/clades-2023-11/europe/2m

### Pre-merge checklist

- [x] ncov file updates:
  - defaults/clades.tsv
  - defaults/clade_emergence_dates.tsv
  - defaults/clade_hierarchy.tsv
  - defaults/clades_display_names.yml
  - defaults/color_ordering.tsv
  - defaults/emerging_lineages.tsv (if needed)
- [x] Explain in PR why we are elevating
- [x] Check trial builds:
  - [x] https://nextstrain.org/staging/ncov/gisaid/trial/clades-2023-11/global/1m
  - [x] https://nextstrain.org/staging/ncov/gisaid/21L/trial/clades-2023-11/global/1m
  - [x] https://nextstrain.org/staging/ncov/open/trial/clades-2023-11/global/1m
- [x] PR approval

### Post merge checklist

- [ ] Add new variant (with new name) to Nextclade dataset
- [ ] Trigger full runs on GISAID & Genbank once Nextclade updated
- [ ] Update [clade diagram figure](https://github.com/nextstrain/ncov-clades-schema)
- [ ] Tweet about new variant

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Fixed 23G (XBB.1.5.70) being grey here: 
https://github.com/nextstrain/ncov/pull/1087/commits/094cf7c679fbfbd13e54a19fd5476f9eeb05f1d6#diff-b21bf394f8cd27132586ca077908fb26785c0fd166c999f154ec3f628f849cb9L34037-L34039
image

**Comment by trvrb** [comment]
Looks great! Thanks for putting the PR together.

**Review by trvrb — APPROVED** [review]

**Comment by Codes1985** [comment]
Hello @corneliusroemer!  Thank you for everything you and other members of the Nextclade team continue to do for the community!  I noticed in the new Nextclade schematic that BA.2.86 is labelled as "22I" rather than "23I".

Thank you and take care,
Cody

**Comment by corneliusroemer** [comment]
Thanks @Codes1985! I've fixed it, might take a few minutes or hours to show if you don't empty your cache

**Comment by corneliusroemer** [comment]
The PR text for prevalence in various countries for 23G and 23H was mixed up, thanks @emmahodcroft for raising this. I have now edited it to be correct.

**Pull request merged**
