### PR TITLE
Metadata cleanups for originating/submitting labs

### LINKED ISSUE #333: Some metadata cleanups to avoid inconsistencies in lab filtering/credit
A few metadata elements have typos or other data-entry issues that are causing near-duplicate entries in the various filter options available at the bottom of the report. I am listing them here in this issue and submitting a PR to resolve the ones that seem like obvious fixes.

- Strain Hangzhou/HZ185/2020 submitting lab "Insepction Center" -> "Inspection Center"
- "University of Wisconsin - Madison AIDS Vaccine Research Laboratory" appears with five different spacing/punctuation variants, normalized them
- "State Key Laboratory for Diagnosis and Treatment of Infectious Diseases, National Clinical Research Center for Infectious Diseases, First Affiliated Hospital, Zhejiang University School of Medicine, Hangzhou, China. 310003" appears with and without trailing period after 'China'
- "Sequencing and Bioinformatics Service and Molecular Epidemiology Research Group. FISABIO-Public Health" appears with and without a trailing period
- "National Influenza Center, Indian Council of Medical Research - National Institute of Virology" has inconsistent spacing in two strains
- "Laboratoire Nationale de Sante, Microbiology, Virology" spelled both 'National' and 'Nationale'
- "Instituto Adolfo Lutz Interdisciplinary Procedures Center, Strategic Laboratory" inconsistent use of commas, inconsistent inclusion of letter "s" in interdisciplinary
- "Department of Laboratory Medicine, Lin-Kou Chang Gung Memorial Hospital, Taoyuan, Taiwan" extra period after "Taiwan" in one case
- "Department of Infection, Immunity and Cardiovascular Disease, The Florey Institute, The Medical School, University of Sheffield" extra space in two records
- "Instituto Nacional de Salud, Universidad Cooperativa de Colombia, Instituto Alexander von Humboldt, Imperial College-London, London School of Hygiene & Tropical Medicine" - inconsistent use of commas

### PR DESCRIPTION
**Pull request by brianpardy**
### Description of proposed changes    
Resolve metadata inconsistencies in submitting/originating lab columns due to spelling, spacing, and other punctuation differences that have accumulated

### Related issue(s)  
Fixes #333 

### Testing
No behavior changes, only visible differences should be a reduction in duplicate filter options at the bottom of the report where e.g. 12 strains come from a particular lab while 2 other strains come from a slightly different spelling variation of that lab.

### CODE REVIEW

**Comment by brianpardy** [comment]
I see conflicts now in this PR, if it would be useful for me to re-submit an updated one later against the current master with these and other metadata cleanups I can, otherwise I will just leave this be.

**Comment by emmahodcroft** [comment]
@brianpardy thank you so much for all this work!!

Unfortunately we pull this information directly from GISAID at every run. We could set up a script to correct this, but this is a problem that we'd need to keep on top of at every new sequence added, and at the moment I am not sure we will have the resources to do this...!

I'll leave this open to see what some other Nextstrain people think. I want to say again - thank you for the effort! I wish it was as simple as fixing just once! :)

**Comment by brianpardy** [comment]
Thanks @emmahodcroft, I had a suspicion this either needed to be fixed in the sequence-storage system you all use or directly at GISAID. I may be able to come up with a script that identifies and adjusts the 'known' inconsistencies but I recognize the overhead it adds to maintain and insert it into the pipeline. If I come up with anything potentially useful I'll PR it here with the understanding I'm obligating myself to maintain it!

**Comment by brianpardy** [comment]
This PR is superseded by my new PR #342 and can be closed as needed.

**Pull request closed without merging**
