### PR TITLE
Send Slack message on Regions deployment failure

### PR DESCRIPTION
**Pull request by kairstenfay**
Send a Slack notification if any part of the Snakemake Regions job
errors out.

----

Note: I only added this functionality in Snakefile_Regions, because that was the only file that was configured to send Slack requests.

### CODE REVIEW

**Comment by kairstenfay** [comment]
[Report failed nextstrain/ncov builds to Slack](https://trello.com/c/WOzJ4sLz/489-report-failed-nextstrain-ncov-builds-to-slack)

**Comment by tsibley** [comment]
Thanks! This is a great start. I rebased onto master and push some additional changes on top. Would you take a look?

I haven't tested this fully due to issues with building locally, but I'll keep pursuing that.

**Comment by tsibley** [comment]
I've fully tested this locally now and it works as expected.

**Comment by kairstenfay** [comment]
Looks good @tsibley ! Thanks for the changes.

**Pull request merged**
