### PR TITLE
Reorganize repo for easy external use + add extensive tutorial / docs

### PR DESCRIPTION
**Pull request by sidneymbell**
## Goal  
The goal of this PR is to make it as easy as possible for external users, with varying levels of technical expertise, to utilize Nextstrain for their local analyses. 

## Primary changes:  
- Renaming / reorganizing many of the files to be more explicit and clear. 
While there are tradeoffs to this (i.e., more keystrokes), I find it far less intimidating and much clearer for the novice user. 

- Adding extensive documentation to get new users up and running in <1 hr, as well as guide more advanced users through useful customization options. 

## Testing  
I went through and methodically and updated all the paths + tested that everything runs as-expected on my box, but **please test this branch** to ensure I didn't miss any references! These things can be messy.

## Known to-do's:  
- [ ] [me + team] Figure out why the `example` profile gives an author-related error during `export`
- [ ] [team] Please test this branch  
- [x] [team] Please read through documentation to ensure accuracy and clarity  
- [x] [me] Update internal links now that this tutorial has a stable-ish home

__After merge__
- [x] [me] Once this branch is merged, deploy to github pages and add a link to nextstrain.org/docs/tutorials  
- [ ] [me] Once merged and stable, update the example dataset and put together a heuristic interpretation guide for questions commonly asked by departments of public health. I'll make a detailed issue so we can tag-team this.

### CODE REVIEW

**Comment by emmahodcroft** [comment]
Ok, this a lot to go through, so this is probably going to be a little here-there-and-everywhere... apologies in advance! Thanks again for doing this Sidney, and overall I think this is looking good. I like the moving of the scripts and rules into another folder - I think this tidies things up nicely. But I'm unsure if we should call it `snakemake` - as this is very close to the `.snakemake` folder that's generated by snakemake - might cause some confusion! 

Overall I think we just need to be careful to find a balance here - while we want to make this friendly for beginners, this is also the repository that runs our builds - I think we should just keep in mind we don't want that to become back-seat to being too beginner-friendly. For example, I think we should try to keep file names & paths 'command-line-friendly' for the build shepherds - it's a small thing, but files that are unique in the first 2-3 letters are just so much easier to work with every day! 😄 

Similarly, it's not clear to me why 'contributor_docs' and 'docs' need to be separated - we have plenty of questions about clades and why data is missing (now moved to 'contributor_docs').
I think it's definitely important we have a good index & clear links from the main page, and links between the tutorial pages, but I think having two docs folders is probably more confusing - and people may not check 'contributor_docs' if they don't think they are 'contributors' - but it's got a lot of info in there.

- I think maybe my PR to your original docs didn't get merged before things got migrated over Sidney? At least, it's still showing as a PR (unmerged) in your github. 

- Seems like maybe `docs/workflow_stucture.md` is deleted rather than moved - is that intentional? Seem it should be moved with the other docs. Also `figures/default_dag.png`. As we've removed all the other figures this could go into `docs/images`, but I this goes in the `workflow_structure.md` file.
 
- I think we can probably keep names a little simpler in some cases, like `seqs_to_exclude.txt` - I think `exclude.txt` is exploratory enough. And these are small things that become a bit annoying when you're working command-line and typing these every day... Same for `helper_scripts` - I think `scripts` is fine. 

- I think `profiles/default` is replaced by `my_analyses/example`, is that right? 

Finally, I'm a little unsure how we best handle the `profiles`/`my_analyses`. I think having a good clear (and clearly labelled) example 'profile' is a really good idea. However, I think it's maybe more confusing to have multiple 'profiles' inside of `my_analyses` when they aren't... your analyses? (And not even just 'profiles' that should be modified/are examples - it also has the real nextstrain builds) 

But, I'm unsure whether making two (`profiles` (or something) containing the 'actual' Nextstrain runs and `my_analyses` containing the examples/things to modify) is clearer or more confusing. Maybe I'm overthinking this - I'd appreciate other thoughts. 

Finally we should have a careful think about how to consolidate examples - @huddlej has pushed up an example using the `--query` argument, but this went to `king-county` which is now gone. Perhaps this should go the 'advanced' Swiss example instead? 

I'll try to sort some edits relating to the above :)

**Comment by emmahodcroft** [comment]
I've merged my edits from yesterday into this branch - so no need to go back to what I did yesterday in the PR!

**Comment by emmahodcroft** [comment]
I've implemented my stuff from yesterday (both PR & my suggestions on Slack) and a lot of the things above. I've tried to be careful to keep things to individual commits so it's easier to track and revert if we so decide.

**Comment by emmahodcroft** [comment]
I've simplified (in number of builds) & better commented the 'advanced' build. I'll try to add a little more to this as examples of some other config stuff etc.

**Comment by sidneymbell** [comment]
Thank you so much for the careful review, @emmahodcroft! Responses below:  

>Seems like maybe docs/workflow_stucture.md is deleted rather than moved - is that intentional? 

Yes, the content was reorganized into other files. 

>I think we can probably keep names a little simpler in some cases, like seqs_to_exclude.txt - I think exclude.txt is exploratory enough. 

Reasonable :)

>I think profiles/default is replaced by my_analyses/example, is that right?

Yup!

>I think it's maybe more confusing to have multiple 'profiles' inside of my_analyses when they aren't... your analyses? ...
But, I'm unsure whether making two (profiles (or something) containing the 'actual' Nextstrain runs and my_analyses containing the examples/things to modify) is clearer or more confusing. 

Super good point! I actually love the idea of splitting out the nextstrain builds from the example / external user-oriented builds. 

>Finally we should have a careful think about how to consolidate examples - @huddlej has pushed up an example using the --query argument, but this went to king-county which is now gone. Perhaps this should go the 'advanced' Swiss example instead?

The `king-county` build is still alive and well, just relabeled as the `example` for clarity. 
I would say the `--query` arg is probably an advanced feature; I'd vote to put it in the Swiss example.

>it's not clear to me why 'contributor_docs' and 'docs' need to be separated  

I'd like to use github pages to serve up just the tutorial markdown files; this sources the `docs` directory. This could then become the landing page for an uncluttered, step-by-step walkthrough, and can be linked directly from `nextstrain.org/docs`.
I'd love other (neater) ideas, though! 

Thanks again for looking at this -- I _so_ appreciate it!

**Comment by sidneymbell** [comment]
Thank you so much, @huddlej!! 

Per our video chat, I've done the following:  
* Moved `scripts` to the top level
* Moved `envs` `schemas` and `snakemake_rules` to a new `workflow` dir  
* Renamed `helpers.smk` -> conventional `common.smk` 
* Renamed `*_analyses` to `*_config` dirs, which I love -- so clean!!  

This should now be ready to test! 

Later this afternoon, I'll split the tutorial docs to their own PR, add your changes, and merge so it's ready to demo tomorrow.  Hoping to get the rest of this PR merged by Thurs at the latest, but this gives us some wiggle room.

Again, huge thanks to both @huddlej and @emmahodcroft for helping to get this over the finish line!

**Comment by emmahodcroft** [comment]
It might be good for me to have a quick chat somehow with one or both of you to catch up on the changes - I've tried to read through but it's a lot, and I'm worried I've missed something! 

Ensuring all links and references to files (esp the ones in the code) are correct is going to be important, and possibly big job to check :)

The other thing that would be good is to give a summary to build shepherds, in particular of the names of files changing that we use a lot, and any changed build calls (`--profiles /profiles/...` won't be it anymore). Can try to start this...

I don't think I see @huddlej 's `--query` example in anywhere - I'll add this to the Swiss advanced example, but John, I think you're best placed now to know where in docs the example you updated for docs should go. Is it ok to leave this with you? I'll also try and update this one with some other advanced features as demos.

Two final comments - can't tell if anything happened with the 'docs' split again (I think no?) but I'm a little against the name 'contributor docs' - because what was in this originally actually isn't all just for contributors - it had clade info and 'where is my data' info (which is actually opposite - this is for people who just looking for their stuff on our builds!). Happy to split this out, but I think 'contributor' misleads what's in there!

I just noticed that `lat_longs.tsv` has been renamed to `gps_coordinates.tsv`. While is _is_ more descriptive, we use `lat_longs` both in `augur` and in pretty much every other build - I'd rather keep it like this, as it'll be instantly familiar for anyone who's run any other build - or for people who run this build then encounter any other build we've done. While we maybe could have named this better from the start, I think this kind of consistency now is good! 
I'll make this change - the docs all seem to actually still reference this, so it'll mean a few less other changes we need to make ;)

**Comment by trvrb** [comment]
Just a couple things that I caught looking at current state of the `tutorial` branch:

* There are a number of command line prompts that retain the `sarscov2-tutorial` naming, eg:
```bash  
sarscov2-tutorial$ snakemake --profile my_config/example -p  
```

* Output files should be named `ncov_global.json`, instead of `sarscov2_global.json`:
```
`./auspice/sarscov2_global.json`
```
We'll do a repo-wide find and replace to swap `ncov` for `sars-cov-2` when we rename the repo. I'd prefer `sars-cov-2` to `sarscov2`.

* `ordering.tsv` shouldn't be `geographic-ordering.tsv`. It contains orderings for colorings like `recency` and would apply to other traits that don't get default auspice colors (`host` is an obvious thing to add). If you'd like this more explicit, I'd rename to `color_ordering.tsv`.

* I think that the top-level directory `nextstrain_config` should be renamed. I believe that things like https://github.com/nextstrain/ncov/tree/master/profiles/swiss should have a place to be shared. In the `tutorial` branch, it looks like the `swiss` profile was deleted. I'd like to share the `spheres` profile here as well. Maybe renaming to `config_library`?

* I'm finding it confusing to have multiple different usages of "config". In the current `tutorial` branch, "config" refers to both the Auspice config JSON `default_auspice_config.json` and also the snakemake config `default_config.yaml`. What about being explicit with snakemake config and calling these things like `default_workflow_config.yaml` and `my_config/example/workflow_config.yaml`? I suspect it's non-obvious that you should mainly be editing `my_config/example/builds.yaml` instead of `my_config/example/config.yaml`. I'd think to first go for `config` over `builds`.

**Comment by huddlej** [comment]
The multiple "config" references is definitely confusing. I'm less sure of my suggestion to rename `my_analyses` to `my_config` now.

There are at least three different configs in play here:

1.  **Snakemake's workflow config**: this is a dictionary of configuration parameters that can be referenced from within a Snakefile (e.g., `min_length` for filtering sequences, etc.). The conventional location and name for this file in Snakemake workflows is `config/config.yaml`. We override the default config with both our `default_config/default_config.yaml` file and the `builds.yaml` files specified in a given Snakemake profile directory.

2. **Snakemake's profile config**: this is a dictionary of parameters that control how Snakemake is executed on the command line. These parameters are not designed to be accessible within a Snakefile, but they simplify the execution of complex Snakemake commands and also provide a file-based interface to override the workflow config dictionary described above. Snakemake requires a profile directory to contain a `config.yaml` file that specifies these command line parameters.

3. **auspice config**: this is our JSON of auspice settings used in augur export

Anyone who wants to make a new custom build should modify the profile config first to specify how they want Snakemake to run and where their custom workflow config file(s) live. Then they should create/modify those custom workflow config file(s). I originally imagined this working for PHL users like this:

```bash
# Copy the example profile.
cp -R profiles/example_public_health_lab profiles/public_health_seattle_king_county

# Modify the profile config for how users want to run the workflow
vim profiles/public_health_seattle_king_county/config.yaml

# Modify the default builds to use desired subsampling schemes.
vim profiles/public_health_seattle_king_county/builds.yaml
```

The only piece preventing this flow from working right now is that the default subsampling schemes live in `default_config/default_config.yaml` which is yet another file users would have to open. If we copy the default subsampling schemes into our example profiles, users should have all the tools they need to get a simple state-, county-, etc. -level build going. We could even take this a step further and place the default auspice config in example directory, too. @emmahodcroft's [Louisiana build](https://github.com/emmahodcroft/south-usa-sarscov2/tree/master/profiles/south-central) is a perfect example of how this could look.

We need to make clear that profiles allows users to specify multiple custom builds for their group. In this way the connotations of "profile" that @sidneymbell mentioned earlier of authorization, personal settings, etc. are appropriate: profiles define how specific users or groups choose to run a workflow. They are a slightly higher-level kind of configuration.

**Comment by sidneymbell** [comment]
Both really good points, @huddlej and @trvrb! I've implemented suggestions from above that I hope address these :)

### Re: config file naming  
I'm actually OK with there being `config` in all 3 of those places (`auspice_config.json`, `default_config.yaml` and `my_config.yaml`), as they're all places where someone looking to customize an analysis should look. 

I like the idea of a `config_library` instead of just `nextstrain_config`!  _Sidenote: the swiss build is alive and well, it just lives under the `example_advanced_customization` name for clarity._

Per the excellent suggestions above, I've made a couple of changes that may help resolve this:  
- `nextstrain_config` > `config_library`  
- I've added a comment at the top of `my_config.yaml` pointing people to `builds.yaml`
- I've added an example `my_auspice_config.yaml` file

If there's still confusion, we could also consider merging the `builds.yaml` with `my_config.yaml` into one file, but I know @huddlej has thought really carefully about this! :)

### Re: `builds.yaml`, where to put subsampling, etc.
Personally, I'm also OK with having the subsampling over in `default_config`, unless we expect folks to redefine this often? Given they're used across many builds, this makes sense to me. 

### Re: other feedback  
- I've renamed `geographic_ordering` > `color_ordering`  
- I've fixed references to `sarscov2-tutorial` -- thanks for the catch!

## Question re: timeline
I know these are significant changes, but none of them are permanent -- while it's annoying to rename files, a find+replace all keeps it pretty straightforward. All this to say that I'm sure we will continue iterating on this in the future, so long as we have a generally stable base to work from.

**Do you feel it would be possible to submit remaining comments on naming and structure by midday tomorrow (PST)?** If possible, I'd really like for us to have time to test and release by the end of the week.

**Comment by sidneymbell** [comment]
# Summary of changes  

## Additions and updates    
- README is updated  
- Adds in-depth tutorial to `docs/` and accompanying github pages setup files  
- `data/` now contains example data that should remain packaged with the repository  
- `narratives/` now contains only a `template_narrative.md` for new users (not to worry -- all finished Situation Reports are still hosted over in the `nextstrain/narratives` repo)  
- `my_config` now contains extensive `example` (formerly `king-county`) and `example_advanced_customization` (formerly `swiss`) profiles

## File name changes  
- The main `config.yaml` file is now more precisely labeled as `default_config.yaml`  
- Similarly, `auspice_config.yaml` > `default_auspice_config.yaml`  
- `reference.gb` > `reference_seq.gb`  
- ordering.tsv` > `color_ordering.tsv`  
- `config` > `default_config`, with nextstrain-specific files (e.g., `description.md`) moved to `default_config/nextstrain/`  
- `profiles` is now `config_library`, with nextstrain-specific builds labeled with `nextstrain_*`  


## Structural changes  
To improve repo clarity and approachability for new users, the following files have been reorganized.

- Workflow-related files now live in a `workflow` directory, rather than the top level  
  - `envs` > `workflow/envs`  
  - `schemas` > `workflow/schemas`  
  - `rules` > `workflow/snakemake_rules`  

(Reiterated from last section because they're important :)
- `config` > `default_config`, with nextstrain-specific files (e.g., `description.md`) moved to `default_config/nextstrain/`  
- `profiles` is now `config_library`, with nextstrain-specific builds labeled with `nextstrain_*`

**Comment by huddlej** [comment]
Everything is working for me in my tests so far. I'm running the example build now to see if I can recreate the auspice author issue. Otherwise, I think this looks good to merge.

> Personally, I'm also OK with having the subsampling over in default_config, unless we expect folks to redefine this often? Given they're used across many builds, this makes sense to me.

I guess that's the big question: how will people actually use this? But, I just noticed that the advanced example defines custom subsampling schemes, so that's a perfect starting point for people who want to go that route.

Thank you again for all of your hard work on this @sidneymbell!

**Comment by huddlej** [comment]
@sidneymbell I recreated the author error with the example build. It is a [data-dependent bug in augur](https://github.com/nextstrain/augur/issues/571) and not specifically a problem with the example build. It may be luck that we haven't encountered it before now.

**Comment by rneher** [comment]
Sorry I am a bit late to the party here. But things are moving fast. I realize there was already a lot of back and forth here, but I find a couple of things really confusing. 

 * `default_config/nextstrain` contains nextstrain specific things and other files like `gisaid_clades.tsv`
 * `config_library` contains the remaining nextstrain specific things. 
 * I much prefer `profiles` to `config_library`. It contains profiles passed to snakemake with the argument `--profiles`. Maybe call is `user-profiles`. `my_config` should be `profile_template` or similar. 

This is going to be a pretty messy merge, mostly because preliminary version of the docs where ported rather than merged into master. But comparing a few files doesn't seem too bad.

**Comment by emmahodcroft** [comment]
> I know these are significant changes, but none of them are permanent -- while it's annoying to rename files, a find+replace all keeps it pretty straightforward. All this to say that I'm sure we will continue iterating on this in the future, so long as we have a generally stable base to work from.

I'd actually be pretty against this. I'd rather us take longer and get it right - this is already a lot of files and a lot names that are still not absolutely clear, and I think changing the names more when people jump onto the tutorial (and from the feedback yesterday I do think people are going to jump onto this tutorial!) is going to make life hard for people. I know Sidney's last day is Friday but we can do the merge ourselves on Monday if we need the weekend/a couple days to finalise these decisions. I think it'll be much clearer for everyone if we don't have to change file names right after we introduce them...

On the other hand, though, I'm ok with things like, copying over `default_auspice_config.json` into the example profiles later if we find from feedback this is clearer. I think that kind of minor change is ok. 

I'll try to maybe improve commenting on both example files so that, for example, the simple example has a comment that says 'check out the advanced example if you want to specify your own subsampling scheme!'

**Comment by emmahodcroft** [comment]
Having looked at this some more - I recognise that there has been *so* much thought gone into the `config`/`profiles` thing, but I'm still finding this confusing.... 

The fact that the profiles folders are now `my_config` and `config_library` - but `default_config` is something entirely separate (not profiles) I'd say is not intuitive at all. It's just too much configs.

I think Richard has a point about using `--profiles` to call a 'profile'. However, we could maybe also switch to a third option - 'recipes' or 'instructions'. But I think we may need to move away from 'config'. 

I'm also a little uncertain about having `nextstrain` within `default_config` - I think this division is pretty arbitrary. Almost everything in `default_config`, is fairly nextstrain-specific (I don't think `gisaid_clades.tsv` is more nextstrain specific than `clades`... quite the opposite, actually!).  I'm also hesitant to separate `default_auspice_config.json` from `nextstrain_auspice_config_gisaid.json` and `nextstrain_auspice_config_zh.json` as these are actually 3 versions of the same thing, and they *must* stay in sync, or we get errors. It's already very hard to remember if you change the first, you have to change the second (for Nextstrain builds), and I've caught this a couple times. Not sure I have a good solution here.

The time zones are making discussion non-trivial for this, I recognise. But as I say above - I'd rather us hash this out properly so we don't have any major renamings anytime soon, even if that takes a couple extra days.

**Comment by emmahodcroft** [comment]
README.md still has some `XXX` links in it. Do links in README work?

I can't find where the 'Getting Started' page that serves up as the front page for https://nextstrain.github.io/ncov/ is located - to add a link to the full install instructions. 

Where is `assign_clades.py` script?

**Comment by emmahodcroft** [comment]
Ok, for build shepherds I don't think that much has changed now, but depending on final names, this may need updating:

- `config` is now `default_config`
- `exclude.txt`, `include.txt`, `lat_longs.tsv` are all the same; `orderings.tsv` is now `color_ordering.tsv`
- `rules/nextstrain_exports.smk` is now `workflow/snakemake_rules/export_for_nextstrain.smk`

The 'finish build' commands are slightly different, as the profile is in a different place, but they are pretty similar. Changes have been made in `export_for_nextstrain.smk` to reflect the updates:

```
# To update ordering/lat_longs after AWS download:
#   snakemake --touch --forceall --profile config_library/nextstrain
#   snakemake --profile config_library/nextstrain clean_export_regions
#   snakemake --profile config_library/nextstrain export_all_regions
# When done adjusting lat-longs & orders, remember to run
#   snakemake --profile config_library/nextstrain all_regions
# to produce the final Auspice files!
```

**Comment by trvrb** [comment]
Thanks all for the detailed discussion. I agree with @emmahodcroft's comment that "it's just too much configs." I think clearer to separate labeling. I think helpful prompt for people that these directories are passed in with `--profile`. 

I don't find it strange at all to run `nextstrain build . --profile /my_profile/example_advanced/`. *However...* if we were to go this route, then I'd want to rename `default_config/` to `default_profile/` for consistency and we're back to square one.

Generally, I think the least semantic load is to have a single directory to look in that would have all the configuration dials a user might want to change (this is basically `default_config/`) and then have a single directory (`my_config`) that is close to a 1:1 mapping that overrides these files.

I started this message off with a "we should switch to `user-profiles`", but now feel that the current use of `my_config`, etc... is less confusing.

I also wonder about getting a fresh set of eyes on this. Someone who is somewhat familiar with bioinformatics, but perhaps not with Snakemake.

**Comment by huddlej** [comment]
>  ...then I'd want to rename default_config/ to default_profile/ for consistency...

I think this is the key source of confusion for us and future users. The `default_config` is [the workflow config](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#standard-configuration) and the `default_profile` is [the profile config](https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles). They really need different names, if we want to keep this distinction clear.

**Comment by emmahodcroft** [comment]
I think I've gotten mixed up again (which probably says a lot about naming) - but isn't `default_config` what's currently `config` - contains the clades, description, etc - so we wouldn't want to rename this to `default_profile`, right? That would be either for the example profiles or for the nextstrain profiles... or both.

**Comment by rneher** [comment]
so... there is quite a lot of confusion. We currently have a `config` directory that contains auxillary files like clades etc, including a `config.yaml` file contains nextstrain specific things like slack channels and general build settings like parameters and file names. 

In addition, there are profiles. these HAVE to contain a `config.yaml`. This, as @huddlej pointed out, is the profile config. In our case, contains a `configfile` directive that includes `config/config.yaml` and other profile-specific configurations, along with other parameters passed onto snakemake. 

We can't change the name of the profile config. But we can change the name of the folder with clade definitions and the parameter file `config/config.yaml`. We should not call profiles `config` -- this will simply confuse matters more!

In general, we need to be careful to not change things too much and without warning. Many people use this repo for their own analysis and custom profiles will all break when we move things around (and will break again when we move them again later).

**Comment by trvrb** [comment]
Yes. I agree to be as explicit as possible with naming these different things. "There are just too many configs". I do think having a single directory with things to modify ala https://github.com/nextstrain/ncov/tree/tutorial/my_config/example_advanced_customization will be more approachable for users.

**Comment by sidneymbell** [comment]
Hey @trvrb @rneher @emmahodcroft @huddlej. Thanks for the great discussion today! 

I've updated the repo structure and naming per the proposal. The only additional change was to also move the `include.txt`, etc. into a `supplementary_files` directory. 

**As a first step, please let me know if the current repo structure and file names look right to you. Once I have that OK, I'll spend some time triple-checking that the paths are all updated and everything runs.**

**Comment by rneher** [comment]
thanks, @sidneymbell. I think this is a log more logical. 

I don't have strong feeling regarding the `supplementary_files` directory, but it currently is used inconsistently. It exists in the nextstrain profiles and the defaults dir, but not in the example profiles.

**Comment by emmahodcroft** [comment]
This is almost mostly as a note to self, but we still didn't discuss the `assign_clades.py` script and whether we want to move this to a sub-folder. This would need to be accompanied by changes across the clades posts (virological, our docs, our blog). And we want to be sure this isn't too breaking for people.

**Comment by emmahodcroft** [comment]
Sorry - I've needed to focus on other things today to catch up from this week, so just coming to this now. I've had a look but I think I'd vote against the new `supplementary_files` folder - I think it's not really necessary, and it doesn't really aid clarification - I think it just hides files which people may be better off knowing are there!
Also, it contains a lot of the files the build shepards use every day and it's just that little more annoying to have to type out that much more of a file path 🙃

**Comment by emmahodcroft** [comment]
I think the structure is looking good and I'm happy with where the file names/folders are at, with one caveat of the `supplementary_files` as discussed above. However, I think it's a great feat we've gotten this far, and I think this structure is looking great!! And is more accessible while still being useful to us a builders.

I haven't had a chance to test today, so I think we still need to complete this before a merge, but I think apart from this we are pretty much there.

Couple things to ensure:
- final guide for build-shepards on what's changed
- final version of change-log
- some kind of guide of things that might break for others  (can do this as we test, ex: Swiss build)

And final few random Q's from me:
- Decision needed on `assign_clades.py` (see above) and need to change relevant links if moved
- We seem to have gained a 'Gemfile' in `docs` - is that supposed to be there?
- I can't find where the 'Getting Started' page that serves up as the front page for https://nextstrain.github.io/ncov/ is located - to add a link to the full install instructions. in the Quickstart.

**Comment by sidneymbell** [comment]
@emmahodcroft -- 
>Decision needed on assign_clades.py (see above) and need to change relevant links if moved

If you're alright with it, I'd vote to go ahead and move it to `scripts.py`. Otherwise it's a little random to have it floating by itself?  Entirely your call, though. 

>We seem to have gained a 'Gemfile' in docs - is that supposed to be there?

Thanks for the catch -- fixed!

>I'd vote against the new supplementary_files folder

No problem. Removed :)

**Comment by sidneymbell** [comment]
Alright, folks @trvrb @huddlej @emmahodcroft @rneher. We're just about ready to merge :)

### Remaining merge blockers:
_I've tagged folks below to see who has time to help with this next week; if it doesn't work for you, just let me know! :)_
- [ ] Resolve [issue](https://github.com/nextstrain/ncov/issues/449) with authors-related issue in the example data (@jameshadfield?)
- [ ] Test this branch!  (@huddlej?)
- [ ] During testing, jot down a list of things that might break for others (ex: Swiss build) (@emmahodcroft?)

I'll be mostly out-of-office next week, but once these are ready to go, I'm happy to handle the messy merge and release the tutorial. 
### My remaining to-do's:
- [ ] Merge (slightly messy)  
- [ ] Create new tag on github  
- [ ] Release tutorial  

### Draft release notes  
Updated here: https://github.com/nextstrain/ncov/pull/444#issuecomment-649143293

Thanks so much for your help, everyone! I know it's been a little hectic, but I'm excited to lower the barriers to entry!

**Comment by huddlej** [comment]
@sidneymbell @jameshadfield Just a head's up that I'm already working on [the author issue in augur](https://github.com/nextstrain/augur/issues/571). I'm hoping to get a fix for this in before making the next major augur release.

**Comment by sidneymbell** [comment]
Amazing. Thank you so much, @huddlej!!

**Comment by rneher** [comment]
It would be good to have this either rebased on master or master merged into it to test the merging of this into external repos.

**Comment by rneher** [comment]
so in the above todo, we need a `rebase/merge master` item before the final merge.

**Comment by sidneymbell** [comment]
> It would be good to have this either rebased on master or master merged into it to test the merging of this into external repos.

@rneher Done :)

**Comment by huddlej** [comment]
@emmahodcroft I'm done testing and tweaking (breaking?) things from the Hutch cluster. Everything works well now from this end including the finalizing steps for build shepherds. Do you have any changes from the Swiss side?

To resolve #451, I ended up needing to add more explicit support for custom rules. These are used now in the Nextstrain profile's `builds.yaml` and are also documented here:

https://github.com/nextstrain/ncov/blob/tutorial/docs/customizing-analysis.md#adding-custom-rules

**Comment by rneher** [comment]
bucket list of things I ran into:

 * merge conflict in `my_profiles/example_advanced_customization/builds.yaml`
 * `profiles/swiss/description.md` was add in HEAD, directory moved remotely. (something I need to fix for swiss, but shouldn't affect others -- our swiss profile was essentially gone after merging)
 * all path like `profiles/nextstrain-scicore/cluster.json` need updating
 * references to the default config need updated `config/config.yaml` -> `config/config.yaml`
 * if you used the name data for something, you can't merge...

**Comment by emmahodcroft** [comment]
I'll try to write up a changelog + 'things that might break' (based on Richard's notes above) + shepherd guide tomorrow. I would recommend to merge first thing in Seattle daytime, so that if anything is breaking in for shepherds you've got more support! If too much breaks in EU daytime I'm often reduced to just rolling things back :)

**Comment by emmahodcroft** [comment]
I've made a new file which is a changelog, breaking changes, and developer changes - all in one. It's linked from the top of the README but after a month or two we can move it to the bottom.

https://github.com/nextstrain/ncov/blob/tutorial/docs/change_log_2020-07.md

**Comment by huddlej** [comment]
Thank you for all of the epic work here, @sidneymbell! I'm so glad we got to work with you again on Nextstrain!

**Comment by emmahodcroft** [comment]
Indeed @sidneymbell !! 🎉

**Pull request merged**
