### PR TITLE
Rename template_narrative and fix dataset links [#1135]

### LINKED ISSUE #1135: Fix broken template_narritave link
https://nextstrain.org/community/narratives/nextstrain/ncov/template_narrative 404s; we need to identify a replacement or remove the link from [visualization/narratives.rst](https://github.com/nextstrain/ncov/blob/master/docs/src/visualization/narratives.rst?plain=1#L10).

### PR DESCRIPTION
**Pull request by genehack**
To comply with [file naming convention](https://github.com/nextstrain/nextstrain.org/blob/ceb01dc3740f89ca9f6b47db63f069485b0969fd/src/sources/community.js#L197-L199) for narratives and [Charon's lack of respect for redirection](https://github.com/nextstrain/nextstrain.org/issues/858).

Closes #1135

### CODE REVIEW

**Comment by joverlee521** [comment]
I was checking to see if we can view the narrative on the branch: 

https://nextstrain.org/community/narratives/nextstrain/ncov@fix-narrative-1135/template_narrative -> shows a Bad Request

https://nextstrain.org/community/narratives/nextstrain/ncov@fix-narrative-1135/template/narrative -> shows error accessing dataset, but at least it's a different error!

**Comment by joverlee521** [comment]
> shows error accessing dataset, but at least it's a different error!

Ah, the error is related to https://github.com/nextstrain/nextstrain.org/issues/858. 
Need to update all of the URLs _within_ `narratives/ncov_template_narrative.md`

https://nextstrain.org/ncov/global?legend=closed -> https://nextstrain.org/ncov/gisaid/global/6m?legend=closed 
https://nextstrain.org/ncov/global?c=country -> https://nextstrain.org/ncov/gisaid/global/6m?c=country
https://nextstrain.org/ncov/global?c=region -> https://nextstrain.org/ncov/gisaid/global/6m?c=region

**Comment by genehack** [comment]
> > shows error accessing dataset, but at least it's a different error!
> 
> Ah, the error is related to [nextstrain/nextstrain.org#858](https://github.com/nextstrain/nextstrain.org/issues/858).

Thanks now it works!

**Review by joverlee521 — APPROVED** [review]

**Comment by genehack** [comment]
...now that I've merged this and the branch isn't present any more, what _should_ be the correct link isn't working. 

I've tried 

https://next.nextstrain.org/community/narratives/nextstrain/ncov/template_narrative
https://next.nextstrain.org/community/narratives/nextstrain/ncov/ncov_template_narrative
https://next.nextstrain.org/community/narratives/nextstrain/ncov_template_narrative

**Comment by joverlee521** [comment]
> I've merged this and the branch isn't present any more, what should be the correct link isn't working.

The correct link is now https://nextstrain.org/community/narratives/nextstrain/ncov/template/narrative

I often forget and just go to the main community page to click on the link listed in https://nextstrain.org/community/nextstrain/ncov

**Comment by genehack** [comment]
> The correct link is now https://nextstrain.org/community/narratives/nextstrain/ncov/template/narrative

Thanks!
 
> I often forget and just go to the main community page to click on the link listed in https://nextstrain.org/community/nextstrain/ncov

I will say that the mismatch between the URL and the file name strikes me as a potentially vast source of misunderstanding and frustration.

**Comment by joverlee521** [comment]
> I will say that the mismatch between the URL and the file name strikes me as a potentially vast source of misunderstanding and frustration.

The docs [explain these technical details](https://docs.nextstrain.org/en/latest/guides/share/community-builds.html#technical-details), but we definitely still get questions about URLs.

**Pull request merged**
