### PR TITLE
Allow customisable auspice JSON prefixes

### LINKED ISSUE #488: Provide a configuration parameter for auspice JSON prefixes
**Context**

[Community builds sourced through nextstrain.org/community](https://nextstrain.org/docs/contributing/community-builds) currently require the prefix of each auspice JSON to match the name of the repository where they are hosted (e.g., `zika-columbia_tree.json` in the [zika-columbia repo](https://github.com/blab/zika-colombia/tree/master/auspice), `covidtracker_ca.json` in the [Biohub California build repo](https://github.com/czbiohub/covidtracker/tree/master/auspice)).

However, the auspice JSONs produced by the ncov workflows [all get prefixed by `ncov_`](https://github.com/nextstrain/ncov/blob/26a77de9594f7b1538a07d0c6c7532f5995c3224/Snakefile#L31). Users who want to provide their builds through the community interface need to manually rename their auspice JSONs or add a custom rule to the workflow to automate this.

**Description**

As an alternative to a custom renaming rule, we could provide a configuration parameter like `auspice_json_prefix` as a top-level setting. This setting could default to `ncov` for backwards-compatibility (defined in `defaults/parameters.yaml`), but users could also override the setting in their custom profiles (e.g., `auspice_json_prefix: zika-columbia`). This setting would allow users to automatically produce JSONs that could be hosted from their GitHub repositories.

### PR DESCRIPTION
**Pull request by ignasiialemany**
### Description of proposed changes    
Pull request fix #488 . Add `prefix` to json files inside `auspice` folder. The `prefix` can be specified in `defaults/parameters.yml`.  If it is not specified in `parameters.yml` the code considers the default prefix "ncov" for backward compatibility .

### CODE REVIEW

**Comment by ignasiialemany** [comment]
#488

**Comment by rneher** [comment]
We should revisit this. will necessary for builds from different origins with otherwise conflicting names.

**Comment by rneher** [comment]
@huddlej the merge conflict is minor -- any suggestions regarding naming? `auspice_json_prefix` seems ok to me.

**Comment by huddlej** [comment]
@rneher `auspice_json_prefix` is fine. This PR needs some edits to work with our builds. I'll rebase onto master and push a version to our repo to work from.

**Comment by huddlej** [comment]
Closing this PR in favor of the updated version in https://github.com/nextstrain/ncov/pull/643

**Pull request closed without merging**
