### PR TITLE
Add normalize_lab_metadata.sh for #333

### LINKED ISSUE #333: Some metadata cleanups to avoid inconsistencies in lab filtering/credit
A few metadata elements have typos or other data-entry issues that are causing near-duplicate entries in the various filter options available at the bottom of the report. I am listing them here in this issue and submitting a PR to resolve the ones that seem like obvious fixes.

- Strain Hangzhou/HZ185/2020 submitting lab "Insepction Center" -> "Inspection Center"
- "University of Wisconsin - Madison AIDS Vaccine Research Laboratory" appears with five different spacing/punctuation variants, normalized them
- "State Key Laboratory for Diagnosis and Treatment of Infectious Diseases, National Clinical Research Center for Infectious Diseases, First Affiliated Hospital, Zhejiang University School of Medicine, Hangzhou, China. 310003" appears with and without trailing period after 'China'
- "Sequencing and Bioinformatics Service and Molecular Epidemiology Research Group. FISABIO-Public Health" appears with and without a trailing period
- "National Influenza Center, Indian Council of Medical Research - National Institute of Virology" has inconsistent spacing in two strains
- "Laboratoire Nationale de Sante, Microbiology, Virology" spelled both 'National' and 'Nationale'
- "Instituto Adolfo Lutz Interdisciplinary Procedures Center, Strategic Laboratory" inconsistent use of commas, inconsistent inclusion of letter "s" in interdisciplinary
- "Department of Laboratory Medicine, Lin-Kou Chang Gung Memorial Hospital, Taoyuan, Taiwan" extra period after "Taiwan" in one case
- "Department of Infection, Immunity and Cardiovascular Disease, The Florey Institute, The Medical School, University of Sheffield" extra space in two records
- "Instituto Nacional de Salud, Universidad Cooperativa de Colombia, Instituto Alexander von Humboldt, Imperial College-London, London School of Hygiene & Tropical Medicine" - inconsistent use of commas

### PR DESCRIPTION
**Pull request by brianpardy**
### Description of proposed changes    
This pull request supersedes my earlier metadata changes to normalize spacing, punctuation, and spelling variants in originating/submitting labs. It adds a new script normalize_lab_metadata.sh that makes two calls to sed to convert variants of lab names into standardized forms. The rationale for this is primarily to make the clickable selections at the bottom of the report to filter by specific labs more usable by collapsing variants into a single entity.

Run this script before beginning the snakemake pipeline.

Usage: `scripts/normalize_lab_metadata.sh data/metadata.tsv`

It does not catch all variants, only the obvious ones I felt could be adjusted without changing any meaning or credit.

### Related issue(s)  
Fixes #333   
Supersedes #334 

### Testing
No tests are included in this PR, my testing has been performed by running through the full pipeline and comparing the output with and without running this new data normalization step.  Comments in the script indicate the 'prior state' of lab metadata as seen in auspice without running the script and can be used to compare the results after running the full pipeline.

If this script is incorporated into the full ncov build, I would suggest that it should be run as part of the process to generate metadata.tsv before committing to git, because users who run this script locally will find that future merges result in heavily conflicted metadata files that make merging them far more difficult. For that reason the script leaves a metadata.tsv.bak file with the un-altered metadata, and before any subsequent commits or merges I restore the original metadata.tsv to ease the process.

### CODE REVIEW

**Comment by tolot27** [comment]
Please add:

```diff
diff --git a/scripts/normalize_lab_metadata.sh b/scripts/normalize_lab_metadata.sh
index cadfa96..e823281 100755
--- a/scripts/normalize_lab_metadata.sh
+++ b/scripts/normalize_lab_metadata.sh
@@ -124,6 +124,14 @@ s/\tGuangdong Provincial Institution of Public Health\t/\tGuangdong Provincial I
 /^France/s/Infectieux (IAI) Hospices/Infectieux (IAI), Hospices/;


+# Germany
+##
+# Institut fur Mikrobiologie der Bundeswehr, Munich
+# Bundeswehr Institute of Microbiology
+##
+/^Germany/s/Institut fur Mikrobiologie der Bundeswehr, Munich/Bundeswehr Institute of Microbiology/;
+
+
 # Hangzhou
 ##
 # State Key Laboratory for Diagnosis and Treatment of Infectious Diseases, National Clinical Research Center for Infectious Diseases, First Affiliated Hospital, Zhejiang University School of Medicine, Hangzhou, China 310003 (8)
```

**Comment by rneher** [comment]
@emmahodcroft @kairstenfay Is this something that we have solved at the level of ingest, or is this still an issue?

**Comment by emmahodcroft** [comment]
This is a bit outdated now because `metadata.tsv` is no longer available. However, we could now standardise lab names etc using the `annotations.tsv` file in the `ncov-ingest` repo. This would be with old fashioned brute-force listing rather than a script. I don't know if this is still of interest, but if anyone in this thread would like to discuss this, let me know!

**Comment by trvrb** [comment]
Thanks for the PR @brianpardy! This curation work is now happening as part of https://github.com/nextstrain/ncov-ingest. Closing this PR in favor of `ncov-ingest` scripts.

**Pull request closed without merging**
